version: "3"
volumes:
  db_data:

services:
  app:
    build: '.'
    restart: always
    entrypoint: ["sh", "./docker-entrypoint.sh"]
    command: ["yarn", "start"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env